from pathlib import Path
home = Path(__file__).parent.parent.parent.parent 
# ----- RAW INPUTS ----------------------------------------------------------------------------------------------------------------
# Utility Files
Borough_to_FIP = r'.\1_RAW_INPUTS\BOUNDARY_BOROUGH_FIPS\Borough_FIPS_1.xlsx'
BOUNDARY_tract = r'.\1_RAW_INPUTS\BOUNDARY_CENSUS_TRACT\CSCL_CensusTract2020.shp'
BOUNDARY_nta = r'.\1_RAW_INPUTS\BOUNDARY_NEIGHBORHOOD\2020 Neighborhood Tabulation Areas (NTAs) - Tabular_20240219\2020NeighborhoodTabulationAreasNTAsTabular_20240219.shp'
BOUNDARY_zcta = r'.\1_RAW_INPUTS\BOUNDARY_MODZCTA\Modified Zip Code Tabulation Areas (MODZCTA)_20240219\ModifiedZipCodeTabulationAreasMODZCTA_20240219.shp'
CPI_table = r'.\1_RAW_INPUTS\OTH_CPI\CPIAUCNS.xls'
population_by_tract = r'.\1_RAW_INPUTS\OTH_POPULATION_BY_TRACT\t_pl_p5_ct_update.xlsx'
dashboard_aliases = r'.\1_RAW_INPUTS\OTH_DASHBOARD_ALIASES\URI Dashboard Aliases.xlsx'
# CER - Coastal Erosion
ESL_CER_CEHA_length = r'.\1_RAW_INPUTS\CER_CEHA_AREA\CEHA_Tract_Shoreline_Split_1.shp'
# CSF - Coastal Flooding and CSW - Coastal Winds
ESL_CSF_hazus_bronx = r".\1_RAW_INPUTS\CST_HAZUS\Coastal Flooding 100 Year\Bronx\Bronx_100PFIRM\results.shp"
ESL_CSF_hazus_kings = r".\1_RAW_INPUTS\CST_HAZUS\Coastal Flooding 100 Year\Kings\Kings_100PFIRM\results.shp"
ESL_CSF_hazus_manhattan = r".\1_RAW_INPUTS\CST_HAZUS\Coastal Flooding 100 Year\New York\NewYork_100PFIRM\results.shp"
ESL_CSF_hazus_queens = r".\1_RAW_INPUTS\CST_HAZUS\Coastal Flooding 100 Year\Queens\Queens_100PFIRM\results.shp"
ESL_CSF_hazus_richmond = r".\1_RAW_INPUTS\CST_HAZUS\Coastal Flooding 100 Year\Richmond\Richmond_100PFIRM\results.shp"
ESL_CSW_hazus_wind = r".\1_RAW_INPUTS\CST_HAZUS\Coastal Storms User Defined Storms WIND ONLY\100yr\100\results.shp"
ESL_CST_dot_table = r'.\1_RAW_INPUTS\CST_DOT_COSTS\Summary of Hazard Event Costs.xlsx'
ESL_CST_building_footprints = r'.\1_RAW_INPUTS\CST_SLOSH_AND_BUILDINGS\NYC_Buildings_composite_20240223.shp'
ESL_CST_building_footprints_depth = r'.\1_RAW_INPUTS\CST_SLOSH_AND_BUILDINGS\NYC_Buildings_composite_20240223_flood_depths_1.shp'
ESL_CST_outages_data = r'.\1_RAW_INPUTS\OTH_HH_C\ElectricalOutages.xlsx'
# ERQ - Earthquke
ESL_ERQ_hazus = r'.\1_RAW_INPUTS\ERQ_HAZUS\Earthquakes (5.2M)\results.shp'
# EXH - Extreme Heat
ESL_EXH_emerg_2016 = r'.\1_RAW_INPUTS\EXH_INJURIES\Heat Stress Emergency Department Visits.csv'
ESL_EXH_emerg_data = r'.\1_RAW_INPUTS\EXH_INJURIES\Trends in Heat Stress Emergency Department Visits - Age-Adjusted Rate.csv'
ESL_EXH_hosp_2016 = r'.\1_RAW_INPUTS\EXH_INJURIES\Heat Stress Hospitalizations.csv'
ESL_EXH_hosp_data = r'.\1_RAW_INPUTS\EXH_INJURIES\Trends in Heat Stress Hospitalizations - Age-Adjusted Rate.csv'
ESL_EXH_ecostress_2020 = r'.\1_RAW_INPUTS\EXH_INJURIES\ZonalStats_Ecostress_CT.csv'
# RES - Respiratory Disease
ESL_RES_COVID_deaths = r'.\1_RAW_INPUTS\RES_COVID_DEATHS\covid_cases_backup.csv'
ESL_RES_PVI = r'.\1_RAW_INPUTS\RES_PVI\PIVI_20190627.gdb\PIVI_20190627'
# WIW - Winter Weather
ESL_WIW_deaths_data = r'.\1_RAW_INPUTS\WIW_DEATHS_INJURIES\Trends in Cold Stress Deaths - Number.csv'
ESL_WIW_emerg_2016 = r'.\1_RAW_INPUTS\WIW_DEATHS_INJURIES\Cold Stress Emergency Department Visits.csv'
ESL_WIW_emerg_data = r'.\1_RAW_INPUTS\WIW_DEATHS_INJURIES\Trends in Cold Stress Emergency Department Visits - Age-Adjusted Rate.csv'
ESL_WIW_hosp_2016 = r'.\1_RAW_INPUTS\WIW_DEATHS_INJURIES\Cold Stress Hospitalizations.csv'
ESL_WIW_hosp_data = r'.\1_RAW_INPUTS\WIW_DEATHS_INJURIES\Trends in Cold Stress Hospitalizations - Age-Adjusted Rate.csv'
ESL_WIW_road_cover = r'.\1_RAW_INPUTS\WIW_LAND_COVER\Fraction_Road_by_Tract.csv'
ESL_WIW_snow_data = r'.\1_RAW_INPUTS\WIW_SNOW_REMOVAL\Snow_Removal_Costs.xlsx'
# Mutliple Hazards
HHC_eventtypes = r'.\1_RAW_INPUTS\OTH_HH_C\EventTypes.xlsx'
HHC_stormeventtypes = r'.\1_RAW_INPUTS\OTH_HH_C\StormEventsTypes.xlsx'
HHC_TreeServices = r'.\1_RAW_INPUTS\OTH_HH_C\TreeServices.xlsx'
stormevents_table = r'.\1_RAW_INPUTS\OTH_HH_C\StormEvents.xlsx'
stormeventsboroughs_table = r'.\1_RAW_INPUTS\OTH_HH_C\StormEventBoroughs.xlsx'
# Social Vulnerability
SOV_tract = r'.\1_RAW_INPUTS\SOV_CDC\SVI2022_NEWYORK_tract.gdb\SVI2022_NEWYORK_tract'
# Resilience Capacity
RCA_CC_community_infrastructure_raw = r'.\1_RAW_INPUTS\RCA_COMMUNITY_INFRASTRUCTURE\Community_infrastructure_20240229.shp'
RCA_CC_EO_locations = r'.\1_RAW_INPUTS\RCA_EDUCATION_AND_OUTREACH\NYC_Ready_NY_Events.csv'
RCA_CC_PE_data = r'.\1_RAW_INPUTS\RCA_POLITICAL_ENGAGEMENT\NYC_VoterParticipation.xlsx'
RCA_RR_FP_raw = r'.\1_RAW_INPUTS\RCA_FLOOD_POLICIES\NYC_NFIP_Policies_04192019.shp'
RCA_RC_ACH_raw = r'.\1_RAW_INPUTS\RCA_AC\Adults Reporting Air Conditioning in the Home\ac_shapefile.shp'
RCA_RC_AC_ac_taskforce = r'.\1_RAW_INPUTS\RCA_AC_PROGRAM\ACTF_Optin_20201013.gdb\ACTF_Optin_20201013'
RCA_RC_CC_layer = r'.\1_RAW_INPUTS\RCA_COOLING_CENTER\Cooling_Centers.shp'
RCA_RC_EP_evac_zones = r'.\1_RAW_INPUTS\RCA_HURRICANE_EVAC_ZONES\Hurricane Evacuation Zones\HurricaneEvacuationZones.shp'
RCA_RC_EP_raw = r'.\1_RAW_INPUTS\RCA_HURRICANE_SHELTER\Hurricane Evacuation Centers\HurricaneEvacuationCenters.shp'
RCA_RC_EMA_raw = r'.\1_RAW_INPUTS\RCA_MEDICAL_CAPACITY\NYC_Hospitals.shp'
RCA_RC_SC_layer = r'.\1_RAW_INPUTS\RCA_SHELTER_CAPACITY\Plan_CSP_EC_HS_20240223.shp'
RCA_RC_IE_activation = r'.\1_RAW_INPUTS\OTH_HH_C\EOCActivations.xlsx'
RCA_ML_GI_raw = r'.\1_RAW_INPUTS\RCA_GREEN_INFRASTRUCTURE\NYC_GI_Pts.shp'
RCA_ML_MI_gdb = r'.\1_RAW_INPUTS\RCA_MITIGATION_INVESTMENT\Mitigation_Actions_for_URI_20220708.gdb'
RCA_ML_MI_table = r'.\1_RAW_INPUTS\RCA_MITIGATION_INVESTMENT\NYC_HMP_Projects_Cleaned.xlsx'
RCA_ML_NS_shoreline = r'.\1_RAW_INPUTS\RCA_NATURAL_SHORELINE\DCP_Shoreline_Piers.gdb\DCP_Shoreline_Piers'
RCA_ML_PWF_raw = r'.\1_RAW_INPUTS\RCA_PARKS_WATER_FEATURES\NYC_SprayShowers.shp'
RCA_ML_VC_table = r'.\1_RAW_INPUTS\RCA_VEGETATIVE_COVER\NYC_VegetativeCover_20241001.csv'
RCA_RC_WA_walkscore_csv = r'.\1_RAW_INPUTS\RCA_WALKSCORE\walkscore_1.csv'
# ----- PROCESSED INPUTS -----------------------------------------------------------------------------------------------------------
RCA_CC_CI_score = r'.\2_PROCESSED_INPUTS\901_RCA_CC_CI_SCORE\RCA_CC_community_infrastructure_score.shp'
RCA_CC_EO_score = r'.\2_PROCESSED_INPUTS\902_RCA_CC_EO_SCORE\RCA_CC_education_outreach_score.shp'
RCA_CC_PA_score = r'.\2_PROCESSED_INPUTS\903_RCA_CC_PA_SCORE\RCA_CC_place_attachment_score.shp'
RCA_CC_PE_score = r'.\2_PROCESSED_INPUTS\904_RCA_CC_PE_SCORE\RCA_CC_political_engagement_score.shp'
RCA_ML_MI_score = r'.\2_PROCESSED_INPUTS\905_RCA_ML_MI_SCORE\RCA_ML_MI_score.shp'
RCA_ML_VC_score = r'.\2_PROCESSED_INPUTS\906_RCA_ML_VC_SCORE\RCA_ML_VC_score.shp'
RCA_ML_PW_score = r'.\2_PROCESSED_INPUTS\907_RCA_ML_WPF_SCORE\RCA_ML_WPF_score.shp'
RCA_ML_GI_score = r'.\2_PROCESSED_INPUTS\908_RCA_ML_GI_SCORE\RCA_ML_GI_score.shp'
RCA_RC_EM_score = r'.\2_PROCESSED_INPUTS\909_RCA_RC_EMA_SCORE\RCA_RC_EMA_score.shp'
RCA_RC_WA_score = r'.\2_PROCESSED_INPUTS\910_RCA_RC_WA_SCORE\RCA_RC_WA_score.shp'
RCA_RC_SC_score = r'.\2_PROCESSED_INPUTS\911_RCA_RC_SC_SCORE\RCA_RC_SC_score.shp'
RCA_RC_AC_score = r'.\2_PROCESSED_INPUTS\913_RCA_RC_AC_SCORE\RCA_RC_ac_score.shp'
RCA_RR_MH_score = r'.\2_PROCESSED_INPUTS\914_RCA_RR_MHI_SCORE\RCA_RR_MHI_score.shp'
RCA_RR_HI_score = r'.\2_PROCESSED_INPUTS\915_RCA_RR_HIC_SCORE\RCA_RR_HIC_score.shp'
RCA_ML_NS_score = r'.\2_PROCESSED_INPUTS\916_RCA_ML_NS_SCORE\RCA_ML_NS_score.shp'
RCA_RC_BI_score = r'.\2_PROCESSED_INPUTS\917_RCA_RC_BI_SCORE\RCA_RC_BI_score.shp'
RCA_RC_TR_score = r'.\2_PROCESSED_INPUTS\918_RCA_RC_TR_SCORE\RCA_RC_TR_score.shp'
RCA_RC_EP_score = r'.\2_PROCESSED_INPUTS\919_RCA_RC_EP_SCORE\RCA_RC_EP_score.shp'
RCA_RC_CC_score = r'.\2_PROCESSED_INPUTS\920_RCA_RC_CC_SCORE\RCA_RC_CC_score.shp'
RCA_RR_IE_score = r'.\2_PROCESSED_INPUTS\921_RCA_RR_IE_SCORE\RCA_RR_IE_score.shp'
RCA_RR_FP_score = r'.\2_PROCESSED_INPUTS\922_RCA_RR_FP_SCORE\RCA_RR_FP_score.shp'
RCA_RR_HO_score = r'.\2_PROCESSED_INPUTS\923_RCA_RR_HO_SCORE\RCA_RR_HO_score.shp'
RCA_RC_IN_score = r'.\2_PROCESSED_INPUTS\924_RCA_RC_INE_SCORE\RCA_RC_INE_score.shp'
EXH_ESL_deaths_per_year_tract = r'.\2_PROCESSED_INPUTS\2104_ESL_EXH_LOSS_DEATH\EXH_ESL_deaths_per_year_tract.shp'
ESL_EXH_loss_power = r'.\2_PROCESSED_INPUTS\2105_ESL_EXH_LOSS_POWER\ESL_EXH_loss_power.shp'
ESL_EXT_loss_injury = r'.\2_PROCESSED_INPUTS\2106_ESL_EXH_LOSS_INJURY\ESL_EXH_loss_injury.shp'
ESL_CST_hazus_loss = r'.\2_PROCESSED_INPUTS\3101_ESL_CST_LOSS_HAZUS\ESL_CST_loss_hazus.shp'
ESL_CST_deaths_loss = r'.\2_PROCESSED_INPUTS\3102_ESL_CST_LOSS_DEATH\ESL_CST_loss_death.shp'
ESL_CST_dislocation_loss = r'.\2_PROCESSED_INPUTS\3103_ESL_CST_LOSS_DISLOCATION\ESL_CST_dislocation_loss.shp'
ESL_CST_loss_transportation = r'.\2_PROCESSED_INPUTS\3104_ESL_CST_LOSS_DOT\ESL_CST_loss_transportation.shp'
ESL_CST_loss_tree = r'.\2_PROCESSED_INPUTS\3105_ESL_CST_LOSS_TREE\ESL_CST_loss_tree.shp'
ESL_CST_loss_power = r'.\2_PROCESSED_INPUTS\3106_ESL_CST_LOSS_POWER\ESL_CST_loss_power.shp'
ESL_CER_ecosystem_loss = r'.\2_PROCESSED_INPUTS\4101_ESL_CER_LOSS_ECO\ESL_CER_loss_ecosystem.shp'
ESL_WIW_loss_deaths = r'.\2_PROCESSED_INPUTS\5101_ESL_WIW_LOSS_DEATH\ESL_WIW_loss_death.shp'
ESL_WIW_loss_snow = r'.\2_PROCESSED_INPUTS\5102_ESL_WIW_LOSS_SNOW\ESL_WIW_loss_snow.shp'
ESL_WIW_loss_injury = r'.\2_PROCESSED_INPUTS\5103_ESL_WIW_LOSS_INJURY\ESL_WIW_loss_injury.shp'
ESL_WIW_loss_tree = r'.\2_PROCESSED_INPUTS\5104_ESL_WIW_LOSS_TREE\ESL_WIW_loss_tree.shp'
ESL_WIW_loss_power = r'.\2_PROCESSED_INPUTS\5105_WIW_LOSS_POWER\ESL_WIW_loss_power.shp'
ESL_FLD_hazus_loss = r'.\2_PROCESSED_INPUTS\6101_ESL_FLD_LOSS_PROPERTY\ESL_FLD_loss_property.shp'
ESL_ERQ_hazus_loss = r'.\2_PROCESSED_INPUTS\7101_ESL_ERQ_LOSS_HAZUS\ESL_ERG_hazus_loss.shp'
ESL_RES_death_loss = r'.\2_PROCESSED_INPUTS\8101_ESL_RES_LOSS_DEATH\ESL_RES_death_loss.shp'
ESL_RES_injury_loss = r'.\2_PROCESSED_INPUTS\8102_ESL_RES_LOSS_INJURY\ESL_RES_injury_loss.shp'
ESL_RES_wages_loss = r'.\2_PROCESSED_INPUTS\8103_ESL_RES_LOSS_WAGES\ESL_RES_wages_loss.shp'
ESL_RES_economy_loss = r'.\2_PROCESSED_INPUTS\8104_ESL_RES_LOSS_ECONOMY\ESL_RES_economy_loss.shp'
ESL_EMG_loss = r'.\2_PROCESSED_INPUTS\8201_ESL_EMG_LOSS_DEATH\ESL_RES_death_loss.shp'
ESL_CRN_death_loss = r'.\2_PROCESSED_INPUTS\8301_ESL_CRN_LOSS_DEATH\ESL_CRN_death_loss.shp'
ESL_CRN_injury_loss = r'.\2_PROCESSED_INPUTS\8302_ESL_CRN_LOSS_INJURY\ESL_CRN_injury_loss.shp'
ESL_CYB_econ_loss = r'.\2_PROCESSED_INPUTS\8303_ESL_CYB_LOSS_ECONOMY\ESL_CYB_econ_loss.shp'
OTH_normalize_values = r'.\2_PROCESSED_INPUTS\9998_OTH\gdf_tract_normalize_values.shp'

# ----- OUTPUTS -----------------------------------------------------------------------------------------------------------
OUTPUTS_folder = r'.\3_OUTPUTS'

# ----- PARAMS -------------------------------------------------------------------------------------------------------------
community_resilience_path = r'.\4_CODE\URI\PARAMS\resilience_capacity.csv'
hazard_resilience_path = r'.\4_CODE\URI\PARAMS\hazard_resilience.csv'
consequences_path = r'.\4_CODE\URI\PARAMS\consequences.csv'